apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-statefulset
spec:
  serviceName: "keycloak-service"
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:20.0.5
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
          ports:
            - containerPort: 8080
          args: ["start-dev"]
  volumeClaimTemplates:
    - metadata:
        name: keycloak-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi